function image_processing_gui()
    % ===== INISIALISASI FIGURE DAN KOMPONEN =====
    fig = figure('Name', 'Image Processing GUI - Organized by Tasks', ...
                 'NumberTitle', 'off', ...
                 'Position', [50 50 1400 800], ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none', ...
                 'Resize', 'on');
    
    % Data global
    data = struct();
    data.original_img = [];
    data.processed_img = [];
    data.is_grayscale = false;
    
    % ===== PANEL KIRI: KONTROL =====
    left_panel = uipanel('Parent', fig, ...
                        'Position', [0.01 0.01 0.29 0.98], ...
                        'Title', 'Control Panel', ...
                        'FontSize', 11, ...
                        'FontWeight', 'bold');
    
    % Tombol Load Image
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Load Image', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.955 0.8 0.035], ...
             'FontSize', 10, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.2 0.6 0.9], ...
             'ForegroundColor', 'white', ...
             'Callback', @load_image_callback);
    
    % Checkbox Grayscale
    chk_gray = uicontrol('Parent', left_panel, ...
                        'Style', 'checkbox', ...
                        'String', 'Convert to Grayscale', ...
                        'Units', 'normalized', ...
                        'Position', [0.1 0.915 0.8 0.03], ...
                        'FontSize', 9, ...
                        'Callback', @grayscale_callback);
    
    % Separator line
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.90 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 1: KONVOLUSI CITRA =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 1: KONVOLUSI CITRA', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.875 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Blur Kernel (3x3)', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.835 0.8 0.032], ...
             'FontSize', 8.5, ...
             'Callback', @custom_conv_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Custom Kernel:', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.805 0.8 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left', ...
             'FontWeight', 'bold');
    
    edit_kernel = uicontrol('Parent', left_panel, ...
                           'Style', 'edit', ...
                           'String', '[1 1 1; 1 1 1; 1 1 1]', ...
                           'Units', 'normalized', ...
                           'Position', [0.1 0.775 0.8 0.025], ...
                           'FontSize', 7.5, ...
                           'HorizontalAlignment', 'left', ...
                           'Max', 3);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Apply Custom Kernel', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.745 0.8 0.028], ...
             'FontSize', 8, ...
             'Callback', @apply_custom_kernel_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.735 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 2: SPATIAL & FREQUENCY FILTERING =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 2: SMOOTHING FILTERS', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.71 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    % Spatial Filtering
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Spatial Domain', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.68 0.8 0.02], ...
             'FontSize', 8.5, ...
             'FontWeight', 'bold');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Filter Size (n):', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.655 0.4 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_n = uicontrol('Parent', left_panel, ...
                      'Style', 'edit', ...
                      'String', '10', ...
                      'Units', 'normalized', ...
                      'Position', [0.55 0.655 0.35 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Mean Filter', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.625 0.37 0.028], ...
             'FontSize', 8, ...
             'Callback', @mean_filter_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Gaussian Filter', ...
             'Units', 'normalized', ...
             'Position', [0.53 0.625 0.37 0.028], ...
             'FontSize', 8, ...
             'Callback', @gaussian_filter_callback);
    
    % Frequency Filtering (Lowpass)
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Frequency Domain (Lowpass)', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.59 0.8 0.02], ...
             'FontSize', 8.5, ...
             'FontWeight', 'bold');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Cutoff D0:', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.565 0.4 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_d0 = uicontrol('Parent', left_panel, ...
                       'Style', 'edit', ...
                       'String', '30', ...
                       'Units', 'normalized', ...
                       'Position', [0.55 0.565 0.35 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'ILPF', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.535 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @ilpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'GLPF', ...
             'Units', 'normalized', ...
             'Position', [0.375 0.535 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @glpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'BLPF', ...
             'Units', 'normalized', ...
             'Position', [0.65 0.535 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @blpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.52 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 3: HIGHPASS FILTERS =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 3: SHARPENING (HIGHPASS)', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.495 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Cutoff D0:', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.47 0.4 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_d0_hp = uicontrol('Parent', left_panel, ...
                          'Style', 'edit', ...
                          'String', '30', ...
                          'Units', 'normalized', ...
                          'Position', [0.55 0.47 0.35 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'IHPF', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.435 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @ihpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'GHPF', ...
             'Units', 'normalized', ...
             'Position', [0.375 0.435 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @ghpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'BHPF', ...
             'Units', 'normalized', ...
             'Position', [0.65 0.435 0.25 0.028], ...
             'FontSize', 8, ...
             'Callback', @bhpf_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.42 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 4: HIGH-BOOST FILTER =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 4: HIGH-BOOST BRIGHTENING', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.395 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'D0:', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.37 0.15 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_d0_hb = uicontrol('Parent', left_panel, ...
                          'Style', 'edit', ...
                          'String', '30', ...
                          'Units', 'normalized', ...
                          'Position', [0.25 0.37 0.15 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'k factor:', ...
             'Units', 'normalized', ...
             'Position', [0.45 0.37 0.2 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_k = uicontrol('Parent', left_panel, ...
                      'Style', 'edit', ...
                      'String', '2.5', ...
                      'Units', 'normalized', ...
                      'Position', [0.68 0.37 0.22 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Apply High-Boost', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.34 0.8 0.028], ...
             'FontSize', 8.5, ...
             'Callback', @highboost_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.325 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 5: NOISE FILTERING =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 5: NOISE FILTERING', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.3 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Noise Filter Test (All)', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.268 0.8 0.028], ...
             'FontSize', 8.5, ...
             'Callback', @noise_filter_test_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Median (S&P Noise)', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.238 0.8 0.028], ...
             'FontSize', 8.5, ...
             'Callback', @median_filter_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.223 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== NOMOR 7: WIENER MOTION BLUR =====
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'NOMOR 7: WIENER RESTORATION', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.198 0.9 0.025], ...
             'FontWeight', 'bold', ...
             'FontSize', 9.5, ...
             'BackgroundColor', [0.0 0.0 0.0], ...
             'HorizontalAlignment', 'center');
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Length:', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.17 0.25 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_len = uicontrol('Parent', left_panel, ...
                        'Style', 'edit', ...
                        'String', '20', ...
                        'Units', 'normalized', ...
                        'Position', [0.35 0.17 0.15 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'Theta:', ...
             'Units', 'normalized', ...
             'Position', [0.52 0.17 0.2 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_theta = uicontrol('Parent', left_panel, ...
                          'Style', 'edit', ...
                          'String', '45', ...
                          'Units', 'normalized', ...
                          'Position', [0.72 0.17 0.18 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', 'K (noise):', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.14 0.35 0.02], ...
             'FontSize', 8, ...
             'HorizontalAlignment', 'left');
    
    edit_K = uicontrol('Parent', left_panel, ...
                      'Style', 'edit', ...
                      'String', '0.001', ...
                      'Units', 'normalized', ...
                      'Position', [0.45 0.14 0.45 0.023]);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Apply Wiener Filter', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.108 0.8 0.028], ...
             'FontSize', 8.5, ...
             'Callback', @wiener_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'text', ...
             'String', '', ...
             'Units', 'normalized', ...
             'Position', [0.05 0.093 0.9 0.002], ...
             'BackgroundColor', [0.5 0.5 0.5]);
    
    % ===== UTILITY BUTTONS =====
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Save Processed Image', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.053 0.8 0.035], ...
             'FontSize', 9, ...
             'FontWeight', 'bold', ...
             'BackgroundColor', [0.3 0.7 0.3], ...
             'ForegroundColor', 'white', ...
             'Callback', @save_image_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Reset', ...
             'Units', 'normalized', ...
             'Position', [0.1 0.01 0.37 0.035], ...
             'FontSize', 9, ...
             'BackgroundColor', [0.9 0.6 0.2], ...
             'Callback', @reset_callback);
    
    uicontrol('Parent', left_panel, ...
             'Style', 'pushbutton', ...
             'String', 'Exit', ...
             'Units', 'normalized', ...
             'Position', [0.53 0.01 0.37 0.035], ...
             'FontSize', 9, ...
             'BackgroundColor', [0.8 0.3 0.3], ...
             'ForegroundColor', 'white', ...
             'Callback', @(~,~)close(fig));
    
    % ===== PANEL KANAN: DISPLAY IMAGES =====
    right_panel = uipanel('Parent', fig, ...
                         'Position', [0.31 0.01 0.68 0.98], ...
                         'Title', 'Image Display', ...
                         'FontSize', 11, ...
                         'FontWeight', 'bold');
    
    % Axes untuk Original Image
    ax_original = axes('Parent', right_panel, ...
                      'Position', [0.05 0.52 0.43 0.43]);
    title(ax_original, 'Original Image', 'FontSize', 12, 'FontWeight', 'bold');
    axis(ax_original, 'off');
    
    % Axes untuk Processed Image
    ax_processed = axes('Parent', right_panel, ...
                       'Position', [0.52 0.52 0.43 0.43]);
    title(ax_processed, 'Processed Image', 'FontSize', 12, 'FontWeight', 'bold');
    axis(ax_processed, 'off');
    
    % Axes untuk Histogram Original
    ax_hist_orig = axes('Parent', right_panel, ...
                       'Position', [0.05 0.05 0.43 0.40]);
    title(ax_hist_orig, 'Histogram (Original)', 'FontSize', 10);
    
    % Axes untuk Histogram Processed
    ax_hist_proc = axes('Parent', right_panel, ...
                       'Position', [0.52 0.05 0.43 0.40]);
    title(ax_hist_proc, 'Histogram (Processed)', 'FontSize', 10);
    
    % ===== CALLBACK FUNCTIONS =====
    
    function load_image_callback(~, ~)
        [filename, pathname] = uigetfile({'*.jpg;*.png;*.bmp;*.tif', 'Image Files'}, ...
                                        'Select an Image');
        if filename == 0
            return;
        end
        
        data.original_img = imread(fullfile(pathname, filename));
        data.processed_img = [];
        
        axes(ax_original);
        imshow(data.original_img);
        title('Original Image', 'FontSize', 12, 'FontWeight', 'bold');
        
        axes(ax_processed);
        cla;
        title('Processed Image', 'FontSize', 12, 'FontWeight', 'bold');
        axis off;
        
        display_histogram(ax_hist_orig, data.original_img, 'Original');
        
        axes(ax_hist_proc);
        cla;
        title('Histogram (Processed)', 'FontSize', 10);
        
        msgbox('Image loaded successfully!', 'Success');
    end

    function grayscale_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            set(chk_gray, 'Value', 0);
            return;
        end
        
        if get(chk_gray, 'Value') == 1
            if size(data.original_img, 3) == 3
                data.original_img = rgb2gray(data.original_img);
                data.is_grayscale = true;
            end
        else
            msgbox('Reload image to get color version', 'Info');
        end
        
        axes(ax_original);
        imshow(data.original_img);
        title('Original Image', 'FontSize', 12, 'FontWeight', 'bold');
        display_histogram(ax_hist_orig, data.original_img, 'Original');
    end

    function custom_conv_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        mask = [1 1 1; 1 1 1; 1 1 1];
        data.processed_img = konvolusi_citra(data.original_img, mask);
        display_processed();
        msgbox('Blur kernel applied (3x3)', 'Nomor 1');
    end

    function apply_custom_kernel_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        kernel_str = get(edit_kernel, 'String');
        
        try
            kernel = eval(kernel_str);
        catch
            msgbox('Invalid kernel format! Use MATLAB syntax like [1 2 1; 2 4 2; 1 2 1]', 'Error', 'error');
            return;
        end
        
        if ~ismatrix(kernel) || ~isnumeric(kernel)
            msgbox('Kernel must be a numeric matrix!', 'Error', 'error');
            return;
        end
        
        data.processed_img = konvolusi_citra(data.original_img, kernel);
        display_processed();
        msgbox(sprintf('Custom kernel applied (%dx%d)', size(kernel, 1), size(kernel, 2)), 'Nomor 1');
    end

    function mean_filter_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        n = str2double(get(edit_n, 'String'));
        if isnan(n) || n < 1
            msgbox('Invalid filter size!', 'Error', 'error');
            return;
        end
        
        mean_filter = ones(n) / (n^2);
        data.processed_img = konvolusi_citra(data.original_img, mean_filter);
        display_processed();
        msgbox(sprintf('Mean filter applied (%dx%d)', n, n), 'Nomor 2');
    end

    function gaussian_filter_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        n = str2double(get(edit_n, 'String'));
        if isnan(n) || n < 1
            msgbox('Invalid filter size!', 'Error', 'error');
            return;
        end
        
        sigma = n / 6;
        [x, y] = meshgrid(-floor(n/2):floor(n/2), -floor(n/2):floor(n/2));
        gauss_filter = exp(-(x.^2 + y.^2) / (2 * sigma^2));
        gauss_filter = gauss_filter / sum(gauss_filter(:));
        
        data.processed_img = konvolusi_citra(data.original_img, gauss_filter);
        display_processed();
        msgbox(sprintf('Gaussian filter applied (%dx%d)', n, n), 'Nomor 2');
    end

    function ilpf_callback(~, ~)
        apply_frequency_filter('ilpf');
    end

    function glpf_callback(~, ~)
        apply_frequency_filter('glpf');
    end

    function blpf_callback(~, ~)
        apply_frequency_filter('blpf');
    end

    function apply_frequency_filter(filter_type)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        D0 = str2double(get(edit_d0, 'String'));
        if isnan(D0) || D0 < 1
            msgbox('Invalid D0 value!', 'Error', 'error');
            return;
        end
        
        img = data.original_img;
        if size(img, 3) == 3
            img = rgb2gray(img);
        end
        
        image = im2double(img);
        [M, N] = size(image);
        
        [u, v] = meshgrid(0:N-1, 0:M-1);
        D = sqrt((u - N/2).^2 + (v - M/2).^2);
        
        H_ilpf = double(D <= D0);
        H_glpf = exp(-(D.^2) / (2 * (D0^2)));
        n_order = 2;
        H_blpf = 1 ./ (1 + (D./D0).^(2*n_order));
        
        switch filter_type
            case 'ilpf'
                H = H_ilpf;
                fname = 'ILPF';
            case 'glpf'
                H = H_glpf;
                fname = 'GLPF';
            case 'blpf'
                H = H_blpf;
                fname = 'BLPF';
        end
        
        F = fftshift(fft2(image));
        G = F .* H;
        filtered = real(ifft2(ifftshift(G)));
        
        data.processed_img = im2uint8(mat2gray(filtered));
        display_processed();
        msgbox(sprintf('%s applied (D0=%d)', fname, D0), 'Nomor 2 - Lowpass Filter');
    end

    function ihpf_callback(~, ~)
        apply_highpass_filter('ihpf');
    end

    function ghpf_callback(~, ~)
        apply_highpass_filter('ghpf');
    end

    function bhpf_callback(~, ~)
        apply_highpass_filter('bhpf');
    end

    function apply_highpass_filter(filter_type)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        img = data.original_img;
        if size(img, 3) == 3
            img = rgb2gray(img);
        end
        
        D0 = str2double(get(edit_d0_hp, 'String'));
        if isnan(D0) || D0 < 1
            msgbox('Invalid D0 value!', 'Error', 'error');
            return;
        end
        
        [M, N] = size(img);
        P = 2*M;
        Q = 2*N;
        
        image = im2double(img);
        imagep = zeros(P, Q);
        for i = 1:P
            for j = 1:Q
                if i <= M && j <= N
                    imagep(i,j) = image(i,j);
                end
            end
        end
        
        F = fftshift(fft2(imagep));
        
        u = 0:(P-1);
        v = 0:(Q-1);
        idx = find(u > P/2);
        u(idx) = u(idx) - P;
        idy = find(v > Q/2);
        v(idy) = v(idy) - Q;
        
        [V, U] = meshgrid(v, u);
        D = sqrt(U.^2 + V.^2);
        
        switch filter_type
            case 'ihpf'
                H = double(D > D0);
                fname = 'IHPF';
            case 'ghpf'
                H = exp(-(D.^2)./(2*(D0^2)));
                H = 1 - H;
                fname = 'GHPF';
            case 'bhpf'
                D(D == 0) = 0.01;
                n = 2;
                H = 1 ./ (1 + (D0./D).^(2*n));
                fname = 'BHPF';
        end
        
        H = fftshift(H);
        
        G = H .* F;
        G1 = ifftshift(G);
        G2 = real(ifft2(G1));
        G2 = G2(1:M, 1:N);
        
        data.processed_img = mat2gray(G2);
        display_processed();
        msgbox(sprintf('%s applied (D0=%d)', fname, D0), 'Nomor 3 - Highpass Filter');
    end

    function highboost_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        D0 = str2double(get(edit_d0_hb, 'String'));
        k = str2double(get(edit_k, 'String'));
        
        if isnan(D0) || D0 < 1 || isnan(k) || k < 1
            msgbox('Invalid parameters!', 'Error', 'error');
            return;
        end
        
        img = data.original_img;
        if size(img, 3) == 3
            img_gray = rgb2gray(img);
        else
            img_gray = img;
        end
        
        I_gray = im2double(img_gray);
        [M, N] = size(I_gray);
        F = fft2(I_gray);
        F_shifted = fftshift(F);
        [u, v] = meshgrid(-floor(N/2):(ceil(N/2)-1), -floor(M/2):(ceil(M/2)-1));
        D = sqrt(u.^2 + v.^2);
        H_lowpass = exp(-(D.^2) / (2 * (D0^2)));
        H_highboost = (k - 1) + H_lowpass;
        G = H_highboost .* F_shifted;
        G_ishift = ifftshift(G);
        g = real(ifft2(G_ishift));
        data.processed_img = mat2gray(g);
        
        display_processed();
        msgbox(sprintf('High-Boost filter applied (D0=%d, k=%.2f)', D0, k), 'Nomor 4');
    end

    function noise_filter_test_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        I = im2double(data.original_img);
        if size(I,3)==3
            I_gray = rgb2gray(I);
        else
            I_gray = I;
        end
        
        I_sp = imnoise(I_gray,'salt & pepper',0.05);
        I_gs = imnoise(I_gray,'gaussian',0,0.01);
        
        m = 3; n = 3; p = floor(m/2); q = floor(n/2);
        [M,N] = size(I_sp);
        pad = padarray(I_sp,[p q],'replicate');
        min_f = zeros(M,N); max_f = zeros(M,N); median_f = zeros(M,N);
        arith_f = zeros(M,N); geo_f = zeros(M,N); harm_f = zeros(M,N);
        contra_f = zeros(M,N); mid_f = zeros(M,N); alpha_f = zeros(M,N);
        Q = 1.5; alpha = 2;
        
        for i=1:M
            for j=1:N
                block = pad(i:i+m-1,j:j+n-1);
                blockv = block(:);
                min_f(i,j)=min(blockv);
                max_f(i,j)=max(blockv);
                median_f(i,j)=median(blockv);
                arith_f(i,j)=mean(blockv);
                geo_f(i,j)=exp(mean(log(blockv+eps)));
                harm_f(i,j)=m*n/sum(1./(blockv+eps));
                contra_f(i,j)=sum(blockv.^(Q+1))/sum(blockv.^Q+eps);
                mid_f(i,j)=(min(blockv)+max(blockv))/2;
                sorted=sort(blockv);
                trimmed=sorted(alpha+1:end-alpha);
                alpha_f(i,j)=mean(trimmed);
            end
        end
        
        figure('Name', 'Nomor 5: Noise Filter Test', 'Position', [100 100 1200 700]);
        subplot(3,4,1);imshow(I_gray);title('Original');
        subplot(3,4,2);imshow(I_sp);title('Salt & Pepper');
        subplot(3,4,3);imshow(min_f);title('Min');
        subplot(3,4,4);imshow(max_f);title('Max');
        subplot(3,4,5);imshow(median_f);title('Median');
        subplot(3,4,6);imshow(arith_f);title('Arithmetic');
        subplot(3,4,7);imshow(geo_f);title('Geometric');
        subplot(3,4,8);imshow(harm_f);title('Harmonic');
        subplot(3,4,9);imshow(contra_f);title('Contraharmonic');
        subplot(3,4,10);imshow(mid_f);title('Midpoint');
        subplot(3,4,11);imshow(alpha_f);title('Alpha-trimmed');
        subplot(3,4,12);imshow(I_gs);title('Gaussian Noise');
        
        msgbox('Noise filter test displayed in new window', 'Nomor 5');
    end

    function median_filter_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        I = im2double(data.original_img);
        if size(I,3)==3
            I_gray = rgb2gray(I);
        else
            I_gray = I;
        end
        
        I_sp = imnoise(I_gray,'salt & pepper',0.05);
        
        m = 3; n = 3; p = floor(m/2); q = floor(n/2);
        [M,N] = size(I_sp);
        pad = padarray(I_sp,[p q],'replicate');
        median_f = zeros(M,N);
        
        for i=1:M
            for j=1:N
                block = pad(i:i+m-1,j:j+n-1);
                blockv = block(:);
                median_f(i,j)=median(blockv);
            end
        end
        
        data.processed_img = median_f;
        display_processed();
        msgbox('Median filter applied to remove salt & pepper noise', 'Nomor 5');
    end

    function wiener_callback(~, ~)
        if isempty(data.original_img)
            msgbox('Please load an image first!', 'Warning', 'warn');
            return;
        end
        
        len = str2double(get(edit_len, 'String'));
        theta = str2double(get(edit_theta, 'String'));
        K = str2double(get(edit_K, 'String'));
        
        if isnan(len) || isnan(theta) || isnan(K)
            msgbox('Invalid parameters!', 'Error', 'error');
            return;
        end
        
        I = im2double(data.original_img);
        if size(I,3) == 3
            I = rgb2gray(I);
        end
        
        PSF = fspecial('motion', len, theta);
        I_blur = imfilter(I, PSF, 'conv', 'circular');
        H = psf2otf(PSF, size(I));
        G = fft2(I_blur);
        F_est = conj(H) ./ (abs(H).^2 + K) .* G;
        I_restored = real(ifft2(F_est));
        
        data.processed_img = I_restored;
        display_processed();
        msgbox(sprintf('Wiener filter applied (len=%d, theta=%d, K=%.4f)', len, theta, K), 'Nomor 7');
    end

    function display_processed()
        axes(ax_processed);
        imshow(data.processed_img);
        title('Processed Image', 'FontSize', 12, 'FontWeight', 'bold');
        
        display_histogram(ax_hist_proc, data.processed_img, 'Processed');
    end

    function display_histogram(ax, img, img_title)
        axes(ax);
        cla;
        
        if size(img, 3) == 3
            img = rgb2gray(img);
        end
        
        imhist(img);
        title(['Histogram (' img_title ')'], 'FontSize', 10);
        grid on;
    end

    function save_image_callback(~, ~)
        if isempty(data.processed_img)
            msgbox('No processed image to save!', 'Warning', 'warn');
            return;
        end
        
        [filename, pathname] = uiputfile({'*.png', 'PNG Image'; '*.jpg', 'JPEG Image'; ...
                                          '*.bmp', 'Bitmap Image'}, 'Save Processed Image');
        if filename == 0
            return;
        end
        
        imwrite(data.processed_img, fullfile(pathname, filename));
        msgbox('Image saved successfully!', 'Success');
    end

    function reset_callback(~, ~)
        data.original_img = [];
        data.processed_img = [];
        data.is_grayscale = false;
        
        axes(ax_original); cla; title('Original Image'); axis off;
        axes(ax_processed); cla; title('Processed Image'); axis off;
        axes(ax_hist_orig); cla; title('Histogram (Original)');
        axes(ax_hist_proc); cla; title('Histogram (Processed)');
        
        set(chk_gray, 'Value', 0);
        set(edit_kernel, 'String', '[1 1 1; 1 1 1; 1 1 1]');
        set(edit_n, 'String', '10');
        set(edit_d0, 'String', '30');
        set(edit_d0_hp, 'String', '30');
        set(edit_d0_hb, 'String', '30');
        set(edit_k, 'String', '2.5');
        set(edit_len, 'String', '20');
        set(edit_theta, 'String', '45');
        set(edit_K, 'String', '0.001');
        
        msgbox('GUI has been reset!', 'Info');
    end

    % ===== HELPER FUNCTION: KONVOLUSI =====
    function output = konvolusi_citra(image, mask)
        mask = double(mask);
        mask = mask / sum(mask(:));
        
        [m, n] = size(mask);
        pad_h = floor(m/2);
        pad_w = floor(n/2);
        
        image = double(image);
        if ismatrix(image)
            padded = padarray(image, [pad_h pad_w], 'replicate');
            [M, N] = size(image);
            output = zeros(M, N);
            for i = 1:M
                for j = 1:N
                    region = padded(i:i+m-1, j:j+n-1);
                    output(i, j) = sum(sum(region .* mask));
                end
            end
        elseif ndims(image) == 3
            [M, N, C] = size(image);
            output = zeros(M, N, C);
            for c = 1:C
                channel = image(:,:,c);
                padded = padarray(channel, [pad_h pad_w], 'replicate');
                for i = 1:M
                    for j = 1:N
                        region = padded(i:i+m-1, j:j+n-1);
                        output(i, j, c) = sum(sum(region .* mask));
                    end
                end
            end
        end
        
        output = uint8(output);
    end

end